[package]
name = "flint"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "serial",
    "io",
]

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
lazy_static = { version = "1.4.0", features = [ "spin_no_std" ] }
serial = { path = "./serial" }
io = { path = "./io" }
