[package]
name = "flint"
version = "0.1.0"
edition = "2021"

[workspace]

members = [
    "serial",
    "io",
]

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.6"
log = "0.4.14"
serial = { path = "./serial", optional = true }
io = { path = "./io", optional = true }


[features]
default = [ "serial_log" ]
serial_log = [ "serial" ]
